import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navigation from '@/components/Navigation';

const yekan = localFont({ src: '../../public/yekan.ttf' });
const iranSans = localFont({ src: '../../public/iranSans.ttf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface Props {
  children: React.ReactNode;
  // cv: React.ReactNode;
  // aboutme: React.ReactNode;
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="fa" dir="rtl">
      <body className={iranSans.className}>
        <Navigation />
        <div className="page-container">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
